const BE_API_URL = process.env.BE_API_URL || process.env.NEXT_PUBLIC_BE_API_URL || "http://localhost:5000";

function buildBePath(path: string) {
  const base = BE_API_URL.replace(/\/+$/, "");
  if (base.endsWith("/api")) {
    return `${base}${path}`;
  }
  return `${base}/api${path}`;
}

export const beTutorRoutes = {
  signup: () => buildBePath("/tutor/auth/signup"),
  login: () => buildBePath("/tutor/auth/login"),
  me: () => buildBePath("/tutor/auth/me"),
  chapters: () => buildBePath("/tutor/chapters"),
  reorderChapters: () => buildBePath("/tutor/chapters/reorder"),
  chapter: (id: string) => buildBePath(`/tutor/chapters/${id}`),
  finishChapter: (id: string) => buildBePath(`/tutor/chapters/${id}/finish`),
  units: () => buildBePath("/tutor/units"),
  reorderUnits: () => buildBePath("/tutor/units/reorder"),
  unit: (id: string) => buildBePath(`/tutor/units/${id}`),
  unitDeletedEntries: (id: string) => buildBePath(`/tutor/units/${id}/deleted-entries`),
  restoreDeletedUnitLesson: (id: string, lessonId: string) => buildBePath(`/tutor/units/${id}/deleted-lessons/${lessonId}/restore`),
  restoreDeletedUnitExpression: (id: string, expressionId: string) => buildBePath(`/tutor/units/${id}/deleted-expressions/${expressionId}/restore`),
  finishUnit: (id: string) => buildBePath(`/tutor/units/${id}/finish`),
  lessons: () => buildBePath("/tutor/lessons"),
  bulkDeleteLessons: () => buildBePath("/tutor/lessons/bulk-delete"),
  reorderLessons: () => buildBePath("/tutor/lessons/reorder"),
  lesson: (id: string) => buildBePath(`/tutor/lessons/${id}`),
  auditLesson: (id: string) => buildBePath(`/tutor/lessons/${id}/audit`),
  requestLessonAudio: (id: string) => buildBePath(`/tutor/lessons/${id}/request-audio`),
  expressions: () => buildBePath("/tutor/expressions"),
  words: () => buildBePath("/tutor/words"),
  sentences: () => buildBePath("/tutor/sentences"),
  proverbs: () => buildBePath("/tutor/proverbs"),
  bulkDeleteExpressions: () => buildBePath("/tutor/expressions/bulk-delete"),
  bulkDeleteWords: () => buildBePath("/tutor/words/bulk-delete"),
  bulkDeleteSentences: () => buildBePath("/tutor/sentences/bulk-delete"),
  finishExpression: (id: string) => buildBePath(`/tutor/expressions/${id}/finish`),
  finishWord: (id: string) => buildBePath(`/tutor/words/${id}/finish`),
  finishSentence: (id: string) => buildBePath(`/tutor/sentences/${id}/finish`),
  bulkExpressionAudio: (lessonId: string) => buildBePath(`/tutor/expressions/bulk/${lessonId}/generate-audio`),
  bulkWordAudio: (lessonId: string) => buildBePath(`/tutor/words/bulk/${lessonId}/generate-audio`),
  bulkSentenceAudio: (lessonId: string) => buildBePath(`/tutor/sentences/bulk/${lessonId}/generate-audio`),
  expression: (id: string) => buildBePath(`/tutor/expressions/${id}`),
  word: (id: string) => buildBePath(`/tutor/words/${id}`),
  sentence: (id: string) => buildBePath(`/tutor/sentences/${id}`),
  expressionImages: (id: string) => buildBePath(`/tutor/expressions/${id}/images`),
  expressionImageLink: (id: string, linkId: string) => buildBePath(`/tutor/expressions/${id}/images/${linkId}`),
  generateExpressionAudio: (id: string) => buildBePath(`/tutor/expressions/${id}/generate-audio`),
  generateWordAudio: (id: string) => buildBePath(`/tutor/words/${id}/generate-audio`),
  generateSentenceAudio: (id: string) => buildBePath(`/tutor/sentences/${id}/generate-audio`),
  questions: () => buildBePath("/tutor/questions"),
  question: (id: string) => buildBePath(`/tutor/questions/${id}`),
  finishLesson: (id: string) => buildBePath(`/tutor/lessons/${id}/finish`),
  finishQuestion: (id: string) => buildBePath(`/tutor/questions/${id}/finish`),
  images: () => buildBePath("/tutor/images"),
  image: (id: string) => buildBePath(`/tutor/images/${id}`),
  proverb: (id: string) => buildBePath(`/tutor/proverbs/${id}`),
  finishProverb: (id: string) => buildBePath(`/tutor/proverbs/${id}/finish`),
  voiceAudioSubmissions: () => buildBePath("/tutor/voice-audio/submissions"),
  acceptVoiceAudioSubmission: (id: string) => buildBePath(`/tutor/voice-audio/submissions/${id}/accept`),
  rejectVoiceAudioSubmission: (id: string) => buildBePath(`/tutor/voice-audio/submissions/${id}/reject`)
};

export const beTutorAiRoutes = {
  generateBulkChapters: () => buildBePath("/tutor/ai/chapters/generate-bulk"),
  generateBulkUnits: () => buildBePath("/tutor/ai/units/generate-bulk"),
  suggestLesson: () => buildBePath("/tutor/ai/lessons/suggest"),
  refactorLessonContent: (lessonId: string) => buildBePath(`/tutor/ai/lessons/${lessonId}/refactor`),
  previewUnitContentPlan: (unitId: string) => buildBePath(`/tutor/ai/units/${unitId}/generate-content/plan`),
  applyUnitContentPlan: (unitId: string) => buildBePath(`/tutor/ai/units/${unitId}/generate-content/apply`),
  generateUnitContent: (unitId: string) => buildBePath(`/tutor/ai/units/${unitId}/generate-content`),
  reviseUnitContent: (unitId: string) => buildBePath(`/tutor/ai/units/${unitId}/revise`),
  generateExpressions: () => buildBePath("/tutor/ai/expressions/generate"),
  generateWords: () => buildBePath("/tutor/ai/words/generate"),
  generateSentences: () => buildBePath("/tutor/ai/sentences/generate"),
  enhanceExpression: (id: string) => buildBePath(`/tutor/ai/expressions/${id}/enhance`),
  generateProverbs: () => buildBePath("/tutor/ai/proverbs/generate")
};

export const feTutorRoutes = {
  signup: () => "/api/tutor/auth/signup",
  login: () => "/api/tutor/auth",
  me: () => "/api/tutor/auth/me",
  chapters: () => "/api/tutor/chapters",
  reorderChapters: () => "/api/tutor/chapters/reorder",
  chapter: (id: string) => `/api/tutor/chapters/${id}`,
  finishChapter: (id: string) => `/api/tutor/chapters/${id}/finish`,
  units: () => "/api/tutor/units",
  reorderUnits: () => "/api/tutor/units/reorder",
  unit: (id: string) => `/api/tutor/units/${id}`,
  unitDeletedEntries: (id: string) => `/api/tutor/units/${id}/deleted-entries`,
  restoreDeletedUnitLesson: (id: string, lessonId: string) => `/api/tutor/units/${id}/deleted-lessons/${lessonId}/restore`,
  restoreDeletedUnitExpression: (id: string, expressionId: string) => `/api/tutor/units/${id}/deleted-expressions/${expressionId}/restore`,
  finishUnit: (id: string) => `/api/tutor/units/${id}/finish`,
  lessons: () => "/api/tutor/lessons",
  bulkDeleteLessons: () => "/api/tutor/lessons/bulk-delete",
  reorderLessons: () => "/api/tutor/lessons/reorder",
  lesson: (id: string) => `/api/tutor/lessons/${id}`,
  auditLesson: (id: string) => `/api/tutor/lessons/${id}/audit`,
  requestLessonAudio: (id: string) => `/api/tutor/lessons/${id}/request-audio`,
  expressions: () => "/api/tutor/expressions",
  words: () => "/api/tutor/words",
  sentences: () => "/api/tutor/sentences",
  proverbs: () => "/api/tutor/proverbs",
  bulkDeleteExpressions: () => "/api/tutor/expressions/bulk-delete",
  bulkDeleteWords: () => "/api/tutor/words/bulk-delete",
  bulkDeleteSentences: () => "/api/tutor/sentences/bulk-delete",
  finishExpression: (id: string) => `/api/tutor/expressions/${id}/finish`,
  finishWord: (id: string) => `/api/tutor/words/${id}/finish`,
  finishSentence: (id: string) => `/api/tutor/sentences/${id}/finish`,
  bulkExpressionAudio: (lessonId: string) => `/api/tutor/expressions/bulk/${lessonId}/generate-audio`,
  bulkWordAudio: (lessonId: string) => `/api/tutor/words/bulk/${lessonId}/generate-audio`,
  bulkSentenceAudio: (lessonId: string) => `/api/tutor/sentences/bulk/${lessonId}/generate-audio`,
  expression: (id: string) => `/api/tutor/expressions/${id}`,
  word: (id: string) => `/api/tutor/words/${id}`,
  sentence: (id: string) => `/api/tutor/sentences/${id}`,
  expressionImages: (id: string) => `/api/tutor/expressions/${id}/images`,
  expressionImageLink: (id: string, linkId: string) => `/api/tutor/expressions/${id}/images/${linkId}`,
  generateExpressionAudio: (id: string) => `/api/tutor/expressions/${id}/generate-audio`,
  generateWordAudio: (id: string) => `/api/tutor/words/${id}/generate-audio`,
  generateSentenceAudio: (id: string) => `/api/tutor/sentences/${id}/generate-audio`,
  questions: () => "/api/tutor/questions",
  question: (id: string) => `/api/tutor/questions/${id}`,
  finishLesson: (id: string) => `/api/tutor/lessons/${id}/finish`,
  finishQuestion: (id: string) => `/api/tutor/questions/${id}/finish`,
  images: () => "/api/tutor/images",
  image: (id: string) => `/api/tutor/images/${id}`,
  proverb: (id: string) => `/api/tutor/proverbs/${id}`,
  finishProverb: (id: string) => `/api/tutor/proverbs/${id}/finish`,
  voiceAudioSubmissions: () => "/api/tutor/voice-audio/submissions",
  acceptVoiceAudioSubmission: (id: string) => `/api/tutor/voice-audio/submissions/${id}/accept`,
  rejectVoiceAudioSubmission: (id: string) => `/api/tutor/voice-audio/submissions/${id}/reject`
};

export const feTutorAiRoutes = {
  generateBulkChapters: () => "/api/tutor/ai/chapters/generate-bulk",
  generateBulkUnits: () => "/api/tutor/ai/units/generate-bulk",
  suggestLesson: () => "/api/tutor/ai/lessons/suggest",
  refactorLessonContent: (lessonId: string) => `/api/tutor/ai/lessons/${lessonId}/refactor`,
  previewUnitContentPlan: (unitId: string) => `/api/tutor/ai/units/${unitId}/generate-content/plan`,
  applyUnitContentPlan: (unitId: string) => `/api/tutor/ai/units/${unitId}/generate-content/apply`,
  generateUnitContent: (unitId: string) => `/api/tutor/ai/units/${unitId}/generate-content`,
  reviseUnitContent: (unitId: string) => `/api/tutor/ai/units/${unitId}/revise`,
  generateExpressions: () => "/api/tutor/ai/expressions/generate",
  generateWords: () => "/api/tutor/ai/words/generate",
  generateSentences: () => "/api/tutor/ai/sentences/generate",
  enhanceExpression: (id: string) => `/api/tutor/ai/expressions/${id}/enhance`,
  generateProverbs: () => "/api/tutor/ai/proverbs/generate"
};
